### ISSUE TITLE
blacklist_grace_period 这个支持吗，应该怎么配置呢

### ISSUE THREAD

**Issue by FFTU** [QThans/jwt-auth#15]
大佬好，
 /*
    | -------------------------------------------------------------------------
    | Blacklist Grace Period
    | -------------------------------------------------------------------------
    |
    | 当多个并发请求使用相同的JWT进行时，
    | 由于 access_token 的刷新 ，其中一些可能会失败
    | 以秒为单位设置请求时间以防止并发的请求失败。
    |
    */

    'blacklist_grace_period' => env('JWT_BLACKLIST_GRACE_PERIOD', 0),

这个配置项支持吗，应该怎么配置呢，谢谢
现在主要是想解决 “多个并发请求使用相同的JWT进行”

**Comment by QThans** [comment]
暂不支持，并发前先验证。后续会支持。

**Comment by qeq66** [comment]
mark
