### ISSUE TITLE
返回payload是个Object，我怎么转换成数组呢？

### ISSUE THREAD

**Issue by indiboy** [QThans/jwt-auth#16]
或者说我有什么快捷的方式取得用户的信息呢，如userid。新手，不是很懂。

**Comment by lxc939134342** [comment]
不知道你的问题是否解决呢？
我昨天遇到了同你一样的问题，我的解决方案是，将获取到的对象直接转成 string  就可以得到正常的值了
```
            $res=JWTAuth::auth();

            $user_info=[
                'openid'=>(string)$res['openid'],
                'session_key'=>(string)$res['session_key']
            ];
```

**Comment by lxc939134342** [comment]
> 或者说我有什么快捷的方式取得用户的信息呢，如userid。新手，不是很懂。

不知道你的问题是否解决呢？
我昨天遇到了同你一样的问题，我的解决方案是，将获取到的对象直接转成 string  就可以得到正常的值了
```
            $res=JWTAuth::auth();

            $user_info=[
                'openid'=>(string)$res['openid'],
                'session_key'=>(string)$res['session_key']
            ];
```
如果有好点的方案，希望也能分享下

**Comment by indiboy** [comment]
最近没怎么上网，我的解决方式是：
`$payload = JWTAuth::getPayload();
        $member = json_decode(json_encode($payload), true);
        $userid = $member['userid'];`
