### ISSUE TITLE
Fatal error: Cannot instantiate interface thans\jwt\contract\Storage

### ISSUE THREAD

**Issue by kaadon** [QThans/jwt-auth#19]
Fatal error: Cannot instantiate interface thans\jwt\contract\Storage

**Comment by kaadon** [comment]
Fatal error: Cannot instantiate interface thans\jwt\contract\Storage

各位朋友,这个怎么解决?
Friends, how to solve this?

**Comment by qeq66** [comment]
运行 `php think jwt:create`
如果报错**There are no commands defined in the "jwt" namespace.**
请升级thinkphp版本
