### ISSUE TITLE
多台服务器的时候出现这个错误

### ISSUE THREAD

**Issue by Mjc960512** [QThans/jwt-auth#21]
这个错误不知道怎么引起的，无法排查，单台服务器没有这个错误，两台服务器配置是相同的，缓存使用的是redis，用的是thinkphp5.1，evn中的秘钥也相同，烦请作者可以回复一下。
[](u
![89103474-B73C-4293-8D05-85E514DB94F9](https://user-images.githubusercontent.com/41005585/101600810-caccda80-3a36-11eb-8fd3-3def7b0d9b88.png)
rl)

**Comment by Mjc960512** [comment]
```php
// 报错信息是这样的
token signature could not be verified！
```

**Comment by Mjc960512** [comment]
或者希望作者可以让我们自己修改错误返回内容，项目已经上线，老是出现这种错误实在不好

**Comment by Mjc960512** [comment]
自定义错误处理了，但是多态服务器这个问题还是没办法

**Comment by QThans** [comment]
整个多台服务器是没有问题的，密钥配置相同在有效期内是可以验证通过的。

**Comment by QThans** [comment]
烦请通过
![image](https://user-images.githubusercontent.com/18275400/101988739-95deb300-3cd6-11eb-90c2-b5e9de685d1b.png)
这个文件调试输出下，看下密钥、加密类型是否一致。
