### ISSUE TITLE
改了接口方法么

### ISSUE THREAD

**Issue by hidahua** [QThans/jwt-auth#23]
1.1.1
interface Storage
{
    public function set($key, $time = 0);

    public function get($key);

    public function delete($key);
}

1.1.2
interface Storage
{
    public function set($key, $val, $time = 0);

    public function get($key);

    public function delete($key);
}

程序错误提示
NOTICE: PHP message: PHP Fatal error:  Declaration of jwt\Blacklist::set($key, $time = 0) must be compatible with thans\jwt\contract\Storage::set($key, $val, $time = 0) in /var/www/html/extend/jwt/Blacklist.php on line 8

**Comment by qeq66** [comment]
额，是的，增加了一个写入写入值，$val = 时间戳。
