### ISSUE TITLE
刷新token时间是分钟为单位，这里有一处没有乘以60

### ISSUE THREAD

**Issue by lzs66666** [QThans/jwt-auth#25]
![1620471554(1)](https://user-images.githubusercontent.com/32189655/117537206-18736080-b032-11eb-9e96-7d43b500094c.jpg)
![1620471685(1)](https://user-images.githubusercontent.com/32189655/117537207-19a48d80-b032-11eb-8a0f-aa00fd8a9cf4.jpg)

**Comment by QThans** [comment]
已处理
