### ISSUE TITLE
已经设置了跨域情况下，在中间件 使用 JWTAuth::auth();  方法提示跨域

### ISSUE THREAD

**Issue by lijiujing** [QThans/jwt-auth#27]
thinkphp6  在中间件 使用 JWTAuth::auth();  报跨域，注释掉JWTAuth::auth(); 就不报跨域了。因为项目已经 设置了可以跨域

在中间件中使用 ：
class Authorization
{
    public function handle($request, Closure $next)
    {
        try {
            JWTAuth::auth();
        } catch(\Throwable $t) {
            abort(401,'token已经失效');
        }
        return $next($request);
    }
}

提示的跨域错误：
as been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

备注：我觉得跨域应该是服务器设置的，但是使用 JWTAuth::auth()方法 验证token  会报跨域，把JWTAuth::auth() 注释掉 就不报了。可以证明 是使用了 JWTAuth::auth() 方法造成的

**Comment by qeq66** [comment]
跨域跟本扩展无关，建议再仔细检查一下
