### ISSUE TITLE
Could not create token :strpos() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by zhigge** [QThans/jwt-auth#29]
![image](https://user-images.githubusercontent.com/17754665/139772588-b5967d26-27e8-4e99-8277-a7e60cc25dd9.png)

**Comment by QThans** [comment]
请具体描述问题，并附上调用代码。这样的截图无法处理。
另请说明thinkphp和php版本

**Comment by pigwan** [comment]
昨天刚遇到这个问题，已经解决了，但是忘了怎么解决了。。先标记一下。

@QThans  我的是Thinkphp6+php8

**Comment by dbkuaizi** [comment]
这个错误是因为 `config/jwt.php` 配置文件中的 `secret` 加载失败导致的。因为作者设计的这个值是从 env 文件读取，可能是你的.env 文件错误 或者 根本就没有生成 需要执行：`php think jwt:create` 重新生成密钥

**Comment by QThans** [comment]
> se

对
