### ISSUE TITLE
thinkphp6.0+php8版本无法使用?

### ISSUE THREAD

**Issue by ChZhg123** [QThans/jwt-auth#31]
thans/tp-jwt-auth1.2.0需要依赖lcobucci/jwt:3.3.*，但是lcobucci/jwt:3.3.*只支持php5.6或者php7版本

**Comment by NbTOne** [comment]
composer require安装时可以--ignore-platform-reqs忽略检查依赖，临时解决。本来lcobucci/jwt 4 代码改变了很多

**Comment by yuanzhihai** [comment]
composer require yzh52521/jwt-auth 已支持lcobucci/jwt 4.0
