### ISSUE TITLE
文档里的JWTAuth::token()->get()应该是$tokenStr = JWTAuth::getToken()吧，是不是写错了

### ISSUE THREAD

**Issue by 15257741312** [QThans/jwt-auth#33]
源码有getToken方法，没有token()方法
`public function getToken()
    {
        if ($this->token === null) {
            try {
                $this->parseToken();
            } catch (JWTException $e) {
                $this->token = null;
            }
        }

        return $this->token;
    }`

**Comment by QThans** [comment]
没错，你是遇到什么问题了？
