### ISSUE TITLE
在最新版Tp6中报错

### ISSUE THREAD

**Issue by sa1111weaweeaaweawe** [QThans/jwt-auth#36]
`During inheritance of JsonSerializable: Uncaught think\exception\ErrorException: Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in`

测试过好几遍，确实在V6.0.13LTS版本中报错
php版本PHP 7.4.30 (cli)

错误原因未知，只是安装正常流程调用。

**Comment by qeq66** [comment]
PHP7.4未复现，请检查一下你的版本，一般来说这个错误是PHP8.1才会提示

**Comment by coolxitech** [comment]
希望支持PHP8.1

**Comment by QThans** [comment]
> 希望支持PHP8.1

已支持
