### ISSUE TITLE
qeq66的包已经无法适配了，建议修复

### ISSUE THREAD

**Issue by coolxitech** [QThans/jwt-auth#39]
使用RS512会出现无法判断是否为密钥对象的问题了

**Comment by QThans** [comment]
完成

**Comment by coolxitech** [comment]
![图片](https://user-images.githubusercontent.com/20185794/231362798-6ac1f782-f9e7-4eca-ae95-ab072fb0d5d1.png)

**Comment by coolxitech** [comment]
并没有修复，主仓库的包已经更改不再使用is_resource判断了

**Comment by coolxitech** [comment]
![图片](https://user-images.githubusercontent.com/20185794/231363733-64e8ffc2-eac2-4e49-ae45-adb05de90297.png)

**Comment by coolxitech** [comment]
![图片](https://user-images.githubusercontent.com/20185794/231363733-64e8ffc2-eac2-4e49-ae45-adb05de90297.png)

**Comment by QThans** [comment]
> ![图片](https://user-images.githubusercontent.com/20185794/231363733-64e8ffc2-eac2-4e49-ae45-adb05de90297.png)

请再测试下，谢谢！
