### ISSUE TITLE
Creation of dynamic property thans\jwt\provider\JWT\Lcobucci::$signer is deprecated

### ISSUE THREAD

**Issue by tlerbao** [QThans/jwt-auth#46]
Creation of dynamic property thans\jwt\provider\JWT\Lcobucci::$signer is deprecated

1.3.1 突然报这个，暂时无法确定问题，

请教一下大概是什么原因

**Comment by qeq66** [comment]
PHP版本太高，建议使用2.x版本

**Comment by tlerbao** [comment]
嗯，发现了，不知道啥时候给项目搞到 php8 上去了。
