### ISSUE TITLE
自动刷新token时设置请求头异常

### ISSUE THREAD

**Issue by hongzhilin2020** [QThans/jwt-auth#5]
https://github.com/QThans/jwt-auth/blob/c7e980c271e1d4c30583b9456d7b7203d600ee2b/src/middleware/BaseMiddleware.php#L24

> 在最近的TP6.0中，此处应该为
> `return $response->header(['Authorization' => 'Bearer ' . $token]);`

传递的是一个数组而非键值对。

**Comment by QThans** [comment]
已解决
