### ISSUE TITLE
【apache】无法通过header的方式获取到token

### ISSUE THREAD

**Issue by imhzs** [QThans/jwt-auth#8]
由于在helper.php中初始化thans\jwt\provider\JWT类时重新生成了一个Request类导致通过header的方式获取到token，应该使用app("request")的方式从容器中获取request对象

**Comment by leruge** [comment]
helper.php把new改成app，通过header的方式也获取不到token？你的可以吗、

**Comment by leruge** [comment]
这个问题，我找到原因了，被上面这大哥说什么重新实例化一个request类误导一上午，然后我打印请求，发现根本没有authorization这个header头，然后又百度了一下，发现是apache配置的问题，大家去百度apche获取不到authorization相关问题，就可以找到答案，真的烦一些不懂乱说了，浪费我一上午时间。

**Comment by QThans** [comment]
> 由于在helper.php中初始化thans\jwt\provider\JWT类时重新生成了一个Request类导致通过header的方式获取到token，应该使用app("request")的方式从容器中获取request对象

获取是可以获取到的，写法确实不太好

**Comment by QThans** [comment]
解决方法：https://blog.csdn.net/Dorisnzy/article/details/83143364

**Comment by leruge** [comment]
@QThans helper.php中这个Request类改成app('request')吧。

**Comment by leruge** [comment]
有强迫症，你不改了，老是觉得有问题。

**Comment by QThans** [comment]
> 有强迫症，你不改了，老是觉得有问题。

改了改了
